# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/user/github.com/game-pwner/game-pwner/tools/gui/widgets/Dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dashboard(object):
    def setupUi(self, Dashboard):
        Dashboard.setObjectName("Dashboard")
        Dashboard.resize(1055, 999)
        Dashboard.setStyleSheet("")
        Dashboard.setWindowTitle("Dashboard")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1055, 982))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.mainFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.mainFrame.setMinimumSize(QtCore.QSize(800, 0))
        self.mainFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line = QtWidgets.QFrame(self.mainFrame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setVerticalSpacing(3)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.fileEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.fileEdit.setFrame(False)
        self.fileEdit.setReadOnly(True)
        self.fileEdit.setObjectName("fileEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fileEdit)
        self.label_10 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.formatEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.formatEdit.setFrame(False)
        self.formatEdit.setReadOnly(True)
        self.formatEdit.setObjectName("formatEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.formatEdit)
        self.label_11 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.modeEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.modeEdit.setFrame(False)
        self.modeEdit.setReadOnly(True)
        self.modeEdit.setObjectName("modeEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.modeEdit)
        self.label_12 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.typeEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.typeEdit.setFrame(False)
        self.typeEdit.setReadOnly(True)
        self.typeEdit.setObjectName("typeEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.typeEdit)
        self.label_15 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.classEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.classEdit.setFrame(False)
        self.classEdit.setReadOnly(True)
        self.classEdit.setObjectName("classEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.classEdit)
        self.label_18 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.langEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.langEdit.setFrame(False)
        self.langEdit.setReadOnly(True)
        self.langEdit.setObjectName("langEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.langEdit)
        self.label_19 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.bitsEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.bitsEdit.setFrame(False)
        self.bitsEdit.setReadOnly(True)
        self.bitsEdit.setObjectName("bitsEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bitsEdit)
        self.sizeEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.sizeEdit.setFrame(False)
        self.sizeEdit.setReadOnly(True)
        self.sizeEdit.setObjectName("sizeEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.sizeEdit)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.formLayout_4.setVerticalSpacing(3)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_4 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.fdEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.fdEdit.setFrame(False)
        self.fdEdit.setReadOnly(True)
        self.fdEdit.setObjectName("fdEdit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fdEdit)
        self.label_20 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.baddrEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.baddrEdit.setFrame(False)
        self.baddrEdit.setReadOnly(True)
        self.baddrEdit.setObjectName("baddrEdit")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.baddrEdit)
        self.label_21 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.vaEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.vaEdit.setFrame(False)
        self.vaEdit.setReadOnly(True)
        self.vaEdit.setObjectName("vaEdit")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.vaEdit)
        self.label_22 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.canaryEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.canaryEdit.setFrame(False)
        self.canaryEdit.setReadOnly(True)
        self.canaryEdit.setObjectName("canaryEdit")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.canaryEdit)
        self.label_23 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.cryptoEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.cryptoEdit.setFrame(False)
        self.cryptoEdit.setReadOnly(True)
        self.cryptoEdit.setObjectName("cryptoEdit")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cryptoEdit)
        self.label_24 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.nxEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.nxEdit.setFrame(False)
        self.nxEdit.setReadOnly(True)
        self.nxEdit.setObjectName("nxEdit")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.nxEdit)
        self.label_25 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.picEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.picEdit.setFrame(False)
        self.picEdit.setReadOnly(True)
        self.picEdit.setObjectName("picEdit")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.picEdit)
        self.label_26 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.label_34 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.relroEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.relroEdit.setFrame(False)
        self.relroEdit.setReadOnly(True)
        self.relroEdit.setObjectName("relroEdit")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.relroEdit)
        self.staticEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.staticEdit.setFrame(False)
        self.staticEdit.setReadOnly(True)
        self.staticEdit.setObjectName("staticEdit")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.staticEdit)
        self.horizontalLayout_2.addLayout(self.formLayout_4)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setVerticalSpacing(3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_14 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.archEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.archEdit.setFrame(False)
        self.archEdit.setReadOnly(True)
        self.archEdit.setObjectName("archEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.archEdit)
        self.label_16 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.machineEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.machineEdit.setFrame(False)
        self.machineEdit.setReadOnly(True)
        self.machineEdit.setObjectName("machineEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.machineEdit)
        self.label_17 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.osEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.osEdit.setFrame(False)
        self.osEdit.setReadOnly(True)
        self.osEdit.setObjectName("osEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.osEdit)
        self.label_30 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.subsysEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.subsysEdit.setFrame(False)
        self.subsysEdit.setReadOnly(True)
        self.subsysEdit.setObjectName("subsysEdit")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.subsysEdit)
        self.label_27 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.strippedEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.strippedEdit.setFrame(False)
        self.strippedEdit.setReadOnly(True)
        self.strippedEdit.setObjectName("strippedEdit")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.strippedEdit)
        self.label_29 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.relocsEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.relocsEdit.setFrame(False)
        self.relocsEdit.setReadOnly(True)
        self.relocsEdit.setObjectName("relocsEdit")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.relocsEdit)
        self.label_28 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.endianEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.endianEdit.setFrame(False)
        self.endianEdit.setReadOnly(True)
        self.endianEdit.setObjectName("endianEdit")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.endianEdit)
        self.label_31 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.compilationDateEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.compilationDateEdit.setFrame(False)
        self.compilationDateEdit.setReadOnly(True)
        self.compilationDateEdit.setObjectName("compilationDateEdit")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.compilationDateEdit)
        self.label_5 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.compilerEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.compilerEdit.setFrame(False)
        self.compilerEdit.setReadOnly(True)
        self.compilerEdit.setObjectName("compilerEdit")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.compilerEdit)
        self.horizontalLayout_2.addLayout(self.formLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.line_3 = QtWidgets.QFrame(self.mainFrame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.certificateButton = QtWidgets.QPushButton(self.mainFrame)
        self.certificateButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.certificateButton.sizePolicy().hasHeightForWidth())
        self.certificateButton.setSizePolicy(sizePolicy)
        self.certificateButton.setObjectName("certificateButton")
        self.horizontalLayout_7.addWidget(self.certificateButton)
        self.versioninfoButton = QtWidgets.QPushButton(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.versioninfoButton.sizePolicy().hasHeightForWidth())
        self.versioninfoButton.setSizePolicy(sizePolicy)
        self.versioninfoButton.setObjectName("versioninfoButton")
        self.horizontalLayout_7.addWidget(self.versioninfoButton)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.line_2 = QtWidgets.QFrame(self.mainFrame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setVerticalSpacing(3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_32 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.md5Edit = QtWidgets.QLineEdit(self.mainFrame)
        self.md5Edit.setText("")
        self.md5Edit.setFrame(False)
        self.md5Edit.setReadOnly(True)
        self.md5Edit.setObjectName("md5Edit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.md5Edit)
        self.label_33 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.sha1Edit = QtWidgets.QLineEdit(self.mainFrame)
        self.sha1Edit.setText("")
        self.sha1Edit.setFrame(False)
        self.sha1Edit.setReadOnly(True)
        self.sha1Edit.setObjectName("sha1Edit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sha1Edit)
        self.label_8 = QtWidgets.QLabel(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lblEntropy = QtWidgets.QLabel(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEntropy.sizePolicy().hasHeightForWidth())
        self.lblEntropy.setSizePolicy(sizePolicy)
        self.lblEntropy.setText("")
        self.lblEntropy.setObjectName("lblEntropy")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lblEntropy)
        self.horizontalLayout_4.addLayout(self.formLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_5.addWidget(self.mainFrame)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        Dashboard.setWidget(self.dockWidgetContents)

        self.retranslateUi(Dashboard)
        QtCore.QMetaObject.connectSlotsByName(Dashboard)

    def retranslateUi(self, Dashboard):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Dashboard", "OVERVIEW"))
        self.label_2.setText(_translate("Dashboard", "Info"))
        self.label_3.setText(_translate("Dashboard", "File:"))
        self.fileEdit.setText(_translate("Dashboard", "--"))
        self.label_10.setText(_translate("Dashboard", "Format:"))
        self.formatEdit.setText(_translate("Dashboard", "--"))
        self.label_11.setText(_translate("Dashboard", "Mode:"))
        self.modeEdit.setText(_translate("Dashboard", "--"))
        self.label_12.setText(_translate("Dashboard", "Size:"))
        self.label_13.setText(_translate("Dashboard", "Type:"))
        self.typeEdit.setText(_translate("Dashboard", "--"))
        self.label_15.setText(_translate("Dashboard", "Class:"))
        self.classEdit.setText(_translate("Dashboard", "--"))
        self.label_18.setText(_translate("Dashboard", "Language:"))
        self.langEdit.setText(_translate("Dashboard", "--"))
        self.label_19.setText(_translate("Dashboard", "Bits:"))
        self.bitsEdit.setText(_translate("Dashboard", "--"))
        self.sizeEdit.setText(_translate("Dashboard", "--"))
        self.label_4.setText(_translate("Dashboard", "FD:"))
        self.fdEdit.setText(_translate("Dashboard", "--"))
        self.label_20.setText(_translate("Dashboard", "Base addr:"))
        self.baddrEdit.setText(_translate("Dashboard", "--"))
        self.label_21.setText(_translate("Dashboard", "Virtual addr:"))
        self.vaEdit.setText(_translate("Dashboard", "--"))
        self.label_22.setText(_translate("Dashboard", "Canary:"))
        self.canaryEdit.setText(_translate("Dashboard", "--"))
        self.label_23.setText(_translate("Dashboard", "Crypto:"))
        self.cryptoEdit.setText(_translate("Dashboard", "--"))
        self.label_24.setText(_translate("Dashboard", "NX bit:"))
        self.nxEdit.setText(_translate("Dashboard", "--"))
        self.label_25.setText(_translate("Dashboard", "PIC:"))
        self.picEdit.setText(_translate("Dashboard", "--"))
        self.label_26.setText(_translate("Dashboard", "Static:"))
        self.label_34.setText(_translate("Dashboard", "Relro:"))
        self.relroEdit.setText(_translate("Dashboard", "--"))
        self.staticEdit.setText(_translate("Dashboard", "--"))
        self.label_14.setText(_translate("Dashboard", "Architecture:"))
        self.archEdit.setText(_translate("Dashboard", "--"))
        self.label_16.setText(_translate("Dashboard", "Machine:"))
        self.machineEdit.setText(_translate("Dashboard", "--"))
        self.label_17.setText(_translate("Dashboard", "OS:"))
        self.osEdit.setText(_translate("Dashboard", "--"))
        self.label_30.setText(_translate("Dashboard", "Subsystem:"))
        self.subsysEdit.setText(_translate("Dashboard", "--"))
        self.label_27.setText(_translate("Dashboard", "Stripped:"))
        self.strippedEdit.setText(_translate("Dashboard", "--"))
        self.label_29.setText(_translate("Dashboard", "Relocs:"))
        self.relocsEdit.setText(_translate("Dashboard", "--"))
        self.label_28.setText(_translate("Dashboard", "Endianness:"))
        self.endianEdit.setText(_translate("Dashboard", "--"))
        self.label_31.setText(_translate("Dashboard", "Compiled:"))
        self.compilationDateEdit.setText(_translate("Dashboard", "--"))
        self.label_5.setText(_translate("Dashboard", "Compiler:"))
        self.compilerEdit.setText(_translate("Dashboard", "--"))
        self.certificateButton.setText(_translate("Dashboard", "Certificates"))
        self.versioninfoButton.setText(_translate("Dashboard", "Version info"))
        self.label_7.setText(_translate("Dashboard", "Hashes"))
        self.label_6.setText(_translate("Dashboard", "Libraries"))
        self.label_32.setText(_translate("Dashboard", "MD5:"))
        self.label_33.setText(_translate("Dashboard", "SHA1:"))
        self.label_8.setText(_translate("Dashboard", "Entropy:"))


