# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/user/github.com/game-pwner/game-pwner/tools/gui/widgets/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(True)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAttach = QtWidgets.QMenu(self.menubar)
        self.menuAttach.setObjectName("menuAttach")
        self.menuWindows = QtWidgets.QMenu(self.menubar)
        self.menuWindows.setObjectName("menuWindows")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionPID = QtWidgets.QAction(MainWindow)
        self.actionPID.setObjectName("actionPID")
        self.actionCRIU = QtWidgets.QAction(MainWindow)
        self.actionCRIU.setObjectName("actionCRIU")
        self.actionCurrentHelp = QtWidgets.QAction(MainWindow)
        self.actionCurrentHelp.setObjectName("actionCurrentHelp")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionResetLayout = QtWidgets.QAction(MainWindow)
        self.actionResetLayout.setObjectName("actionResetLayout")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionMemoryMaps = QtWidgets.QAction(MainWindow)
        self.actionMemoryMaps.setCheckable(True)
        self.actionMemoryMaps.setObjectName("actionMemoryMaps")
        self.actionMemoryView = QtWidgets.QAction(MainWindow)
        self.actionMemoryView.setCheckable(True)
        self.actionMemoryView.setObjectName("actionMemoryView")
        self.actionValueScanner = QtWidgets.QAction(MainWindow)
        self.actionValueScanner.setCheckable(True)
        self.actionValueScanner.setObjectName("actionValueScanner")
        self.actionPointerScanner = QtWidgets.QAction(MainWindow)
        self.actionPointerScanner.setCheckable(True)
        self.actionPointerScanner.setObjectName("actionPointerScanner")
        self.actionCheats = QtWidgets.QAction(MainWindow)
        self.actionCheats.setCheckable(True)
        self.actionCheats.setObjectName("actionCheats")
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionCurrentHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuAttach.addAction(self.actionPID)
        self.menuAttach.addAction(self.actionCRIU)
        self.menuWindows.addAction(self.actionMemoryMaps)
        self.menuWindows.addAction(self.actionMemoryView)
        self.menuWindows.addAction(self.actionValueScanner)
        self.menuWindows.addAction(self.actionPointerScanner)
        self.menuWindows.addAction(self.actionCheats)
        self.menuSettings.addAction(self.actionResetLayout)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuAttach.menuAction())
        self.menubar.addAction(self.menuWindows.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.actionPID.triggered.connect(MainWindow.onActionPID)
        self.actionCRIU.triggered.connect(MainWindow.onActionCRIU)
        self.actionMemoryMaps.triggered['bool'].connect(MainWindow.onActionMemoryMaps)
        self.actionMemoryView.triggered['bool'].connect(MainWindow.onActionMemoryView)
        self.actionValueScanner.triggered['bool'].connect(MainWindow.onActionValueScanner)
        self.actionPointerScanner.triggered['bool'].connect(MainWindow.onActionPointerScanner)
        self.actionCheats.triggered['bool'].connect(MainWindow.onActionCheats)
