# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/user/github.com/game-pwner/game-pwner/tools/gui/widgets/PointerScanner.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PointerScanner(object):
    def setupUi(self, PointerScanner):
        PointerScanner.setObjectName("PointerScanner")
        PointerScanner.resize(846, 573)
        PointerScanner.setStyleSheet("")
        PointerScanner.setWindowTitle("PointerScanner")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnPlus = QtWidgets.QToolButton(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPlus.sizePolicy().hasHeightForWidth())
        self.btnPlus.setSizePolicy(sizePolicy)
        self.btnPlus.setText("+")
        self.btnPlus.setObjectName("btnPlus")
        self.horizontalLayout_4.addWidget(self.btnPlus)
        self.lblAddresses = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblAddresses.setObjectName("lblAddresses")
        self.horizontalLayout_4.addWidget(self.lblAddresses)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.treeAddresses = QtWidgets.QTreeView(self.dockWidgetContents)
        self.treeAddresses.setObjectName("treeAddresses")
        self.verticalLayout.addWidget(self.treeAddresses)
        self.lblSettings = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblSettings.setObjectName("lblSettings")
        self.verticalLayout.addWidget(self.lblSettings)
        self.radioType1 = QtWidgets.QRadioButton(self.dockWidgetContents)
        self.radioType1.setChecked(True)
        self.radioType1.setObjectName("radioType1")
        self.verticalLayout.addWidget(self.radioType1)
        self.radioType2 = QtWidgets.QRadioButton(self.dockWidgetContents)
        self.radioType2.setEnabled(False)
        self.radioType2.setObjectName("radioType2")
        self.verticalLayout.addWidget(self.radioType2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblStep = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblStep.setObjectName("lblStep")
        self.horizontalLayout_5.addWidget(self.lblStep, 0, QtCore.Qt.AlignRight)
        self.spinStep = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinStep.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinStep.setSuffix("")
        self.spinStep.setPrefix("")
        self.spinStep.setMinimum(1)
        self.spinStep.setMaximum(8)
        self.spinStep.setSingleStep(1)
        self.spinStep.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.spinStep.setProperty("value", 4)
        self.spinStep.setDisplayIntegerBase(10)
        self.spinStep.setObjectName("spinStep")
        self.horizontalLayout_5.addWidget(self.spinStep)
        self.lblOffset = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblOffset.setObjectName("lblOffset")
        self.horizontalLayout_5.addWidget(self.lblOffset, 0, QtCore.Qt.AlignRight)
        self.spinOffset = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinOffset.setPrefix("")
        self.spinOffset.setMinimum(1)
        self.spinOffset.setMaximum(1048576)
        self.spinOffset.setProperty("value", 2047)
        self.spinOffset.setDisplayIntegerBase(10)
        self.spinOffset.setObjectName("spinOffset")
        self.horizontalLayout_5.addWidget(self.spinOffset)
        self.lblLevel = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblLevel.setObjectName("lblLevel")
        self.horizontalLayout_5.addWidget(self.lblLevel, 0, QtCore.Qt.AlignRight)
        self.spinLevel = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinLevel.setMinimum(1)
        self.spinLevel.setProperty("value", 3)
        self.spinLevel.setObjectName("spinLevel")
        self.horizontalLayout_5.addWidget(self.spinLevel)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.btnRegions = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnRegions.setEnabled(False)
        self.btnRegions.setObjectName("btnRegions")
        self.verticalLayout.addWidget(self.btnRegions)
        self.btnRegionsF = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnRegionsF.setEnabled(False)
        self.btnRegionsF.setObjectName("btnRegionsF")
        self.verticalLayout.addWidget(self.btnRegionsF)
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnOpen = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnOpen.setEnabled(False)
        self.btnOpen.setObjectName("btnOpen")
        self.horizontalLayout_6.addWidget(self.btnOpen)
        self.comboRecent = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboRecent.setEnabled(False)
        self.comboRecent.setMaxCount(2147483647)
        self.comboRecent.setObjectName("comboRecent")
        self.horizontalLayout_6.addWidget(self.comboRecent)
        self.btnScan = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnScan.setObjectName("btnScan")
        self.horizontalLayout_6.addWidget(self.btnScan)
        self.btnRescan = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnRescan.setEnabled(False)
        self.btnRescan.setObjectName("btnRescan")
        self.horizontalLayout_6.addWidget(self.btnRescan)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblPointers = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblPointers.setObjectName("lblPointers")
        self.horizontalLayout_3.addWidget(self.lblPointers)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.treePointers = QtWidgets.QTreeView(self.dockWidgetContents)
        self.treePointers.setObjectName("treePointers")
        self.verticalLayout_2.addWidget(self.treePointers)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        PointerScanner.setWidget(self.dockWidgetContents)

        self.retranslateUi(PointerScanner)
        QtCore.QMetaObject.connectSlotsByName(PointerScanner)

    def retranslateUi(self, PointerScanner):
        _translate = QtCore.QCoreApplication.translate
        self.lblAddresses.setText(_translate("PointerScanner", "Addresses: 0"))
        self.lblSettings.setText(_translate("PointerScanner", "Settings:"))
        self.radioType1.setText(_translate("PointerScanner", "Backward Pointer Scanner"))
        self.radioType2.setText(_translate("PointerScanner", "Forward Pointer Scanner (slower)"))
        self.lblStep.setText(_translate("PointerScanner", "Step:"))
        self.lblOffset.setText(_translate("PointerScanner", "Max offset:"))
        self.lblLevel.setText(_translate("PointerScanner", "Max level:"))
        self.btnRegions.setText(_translate("PointerScanner", "Regions to scan by Value Scanner..."))
        self.btnRegionsF.setText(_translate("PointerScanner", "Regions to scan by Forward Pointer Scanner..."))
        self.label.setText(_translate("PointerScanner", "Complexity:"))
        self.btnOpen.setText(_translate("PointerScanner", "Open..."))
        self.btnScan.setText(_translate("PointerScanner", "New Scan..."))
        self.btnRescan.setText(_translate("PointerScanner", "Rescan"))
        self.lblPointers.setText(_translate("PointerScanner", "Pointers: 0"))


