# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/user/github.com/game-pwner/game-pwner/tools/gui/widgets/ValueScanner.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ValueScanner(object):
    def setupUi(self, ValueScanner):
        ValueScanner.setObjectName("ValueScanner")
        ValueScanner.resize(845, 400)
        ValueScanner.setStyleSheet("")
        ValueScanner.setWindowTitle("ValueScanner")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblValues = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblValues.setObjectName("lblValues")
        self.verticalLayout_2.addWidget(self.lblValues)
        self.treeValues = QtWidgets.QTreeView(self.dockWidgetContents)
        self.treeValues.setObjectName("treeValues")
        self.verticalLayout_2.addWidget(self.treeValues)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboRecent = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboRecent.setObjectName("comboRecent")
        self.horizontalLayout_2.addWidget(self.comboRecent)
        self.btnScan = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnScan.setObjectName("btnScan")
        self.horizontalLayout_2.addWidget(self.btnScan)
        self.btnReset = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnReset.setEnabled(False)
        self.btnReset.setObjectName("btnReset")
        self.horizontalLayout_2.addWidget(self.btnReset)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.lineValue = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineValue.setObjectName("lineValue")
        self.verticalLayout_3.addWidget(self.lineValue)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboScanType = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboScanType.setObjectName("comboScanType")
        self.comboScanType.addItem("")
        self.comboScanType.addItem("")
        self.comboScanType.addItem("")
        self.comboScanType.addItem("")
        self.comboScanType.addItem("")
        self.comboScanType.addItem("")
        self.horizontalLayout_3.addWidget(self.comboScanType)
        self.comboValueType = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboValueType.setObjectName("comboValueType")
        self.comboValueType.addItem("")
        self.comboValueType.addItem("")
        self.comboValueType.addItem("")
        self.comboValueType.addItem("")
        self.comboValueType.setItemText(3, "int")
        self.comboValueType.addItem("")
        self.comboValueType.setItemText(4, "int8")
        self.comboValueType.addItem("")
        self.comboValueType.setItemText(5, "int16")
        self.comboValueType.addItem("")
        self.comboValueType.setItemText(6, "int32")
        self.comboValueType.addItem("")
        self.comboValueType.setItemText(7, "int64")
        self.comboValueType.addItem("")
        self.comboValueType.setItemText(8, "float")
        self.comboValueType.addItem("")
        self.comboValueType.setItemText(9, "float32")
        self.comboValueType.addItem("")
        self.comboValueType.setItemText(10, "float64")
        self.horizontalLayout_3.addWidget(self.comboValueType)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblStep = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblStep.setObjectName("lblStep")
        self.horizontalLayout_4.addWidget(self.lblStep)
        self.spinStep = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinStep.setMinimum(1)
        self.spinStep.setMaximum(8)
        self.spinStep.setProperty("value", 4)
        self.spinStep.setObjectName("spinStep")
        self.horizontalLayout_4.addWidget(self.spinStep)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.btnRegions = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnRegions.setObjectName("btnRegions")
        self.verticalLayout_3.addWidget(self.btnRegions)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        ValueScanner.setWidget(self.dockWidgetContents)

        self.retranslateUi(ValueScanner)
        self.comboValueType.setCurrentIndex(2)
        self.btnRegions.clicked.connect(ValueScanner.onActionRegions)
        self.btnReset.clicked.connect(ValueScanner.onActionReset)
        self.btnScan.clicked.connect(ValueScanner.onActionScan)
        self.lineValue.textChanged['QString'].connect(ValueScanner.onUservalueChange)
        QtCore.QMetaObject.connectSlotsByName(ValueScanner)

    def retranslateUi(self, ValueScanner):
        _translate = QtCore.QCoreApplication.translate
        self.lblValues.setText(_translate("ValueScanner", "Values: 0"))
        self.btnScan.setText(_translate("ValueScanner", "Scan"))
        self.btnReset.setText(_translate("ValueScanner", "Reset"))
        self.lineValue.setPlaceholderText(_translate("ValueScanner", "Value to scan"))
        self.comboScanType.setItemText(0, _translate("ValueScanner", "Exact value"))
        self.comboScanType.setItemText(1, _translate("ValueScanner", "Greater than..."))
        self.comboScanType.setItemText(2, _translate("ValueScanner", "Less than..."))
        self.comboScanType.setItemText(3, _translate("ValueScanner", "In the range between..."))
        self.comboScanType.setItemText(4, _translate("ValueScanner", "Not in the range between..."))
        self.comboScanType.setItemText(5, _translate("ValueScanner", "Unknown initial value"))
        self.comboValueType.setItemText(0, _translate("ValueScanner", "bytearray"))
        self.comboValueType.setItemText(1, _translate("ValueScanner", "string"))
        self.comboValueType.setItemText(2, _translate("ValueScanner", "number"))
        self.lblStep.setText(_translate("ValueScanner", "Alignment:"))
        self.btnRegions.setText(_translate("ValueScanner", "Regions to scan..."))


